server {
    listen 80;
    server_name rabelodigital.com;

    return 301 http://$server_name$request_uri;
}

server {
    # listen 443 ssl;
    server_name rabelodigital.com;

    # ssl_certificate /etc/nginx/ssl/rabelodigital.com.br.crt;
    # ssl_certificate_key /etc/nginx/ssl/rabelodigital.com.br.key;
    # ssl_protocols       TLSv1.2 TLSv1.3;
    # ssl_ciphers         HIGH:!aNULL:!MD5;

    error_page 404 502 503 504 /manutencao.html;
    
    location = /manutencao.html {
        root /var/www/html;
        internal;
    }


    location /api {
        proxy_pass http://localhost:9000/api;  # A API está rodando na porta 9000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        error_page 502 =502 /502.html;  # Se der erro 502, você pode mostrar algo personalizado ou deixar vazio
    }

    location / {
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}